spring.application.name=Spring_Jpa_part3

spring.datasource.url=jdbc:mysql://localhost:3306/assignment
spring.datasource.username=babulal
spring.datasource.password=me210205

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
